In [2]:
import torch
import numpy as np

In [6]:
# 데이터로 직접 tensor 생성하기
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(f"tensor: \n {x_data} \n")

# numpy 배열로 tensor 생성하기 - 그 반대도 가능
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"numpy_tensor: \n {x_np} \n")

tensor: 
 tensor([[1, 2],
        [3, 4]]) 

numpy_tensor: 
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [7]:
# 다른 텐서로부터 생성하기: 명시적으로 재정의(Override)하지 않으면, 인자로 주어진 텐서의 shape와 datatype을 유지
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7597, 0.1608],
        [0.2285, 0.9941]]) 



In [ ]:
## 무작위(random) 또는 상수(constant) 값을 사용하기

# shape는 tensor의 차원(dimension)을 나타내는 tuple, 아래에서 출력 tensor의 차원을 결정
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7046, 0.9992, 0.9549],
        [0.9029, 0.7789, 0.6779]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [12]:
## 텐서의 속성 Attribute

# 텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.

tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
## 텐서 연산(Operation)

# 기본적으로 tensor는 cpu에 생성
# .to 명령어를 사용하여 (단, GPU의 가용성을 먼저 확인한 후) GPU로 tensor를 명시적으로 이동 가능

# GPU가 존재하면 텐서를 이동합니다. -> 노트북이 내장그래픽이라서 GPU X
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
# Numpy식 표준 인덱싱과 슬라이싱

tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [ ]:
## Tensor 합치기

# torch.cat을 사용해 주어진 차원에 따라 텐서 연결 가능
# torch.cat과 미묘하게 다른 텐서 결합 연산자 torch.stack 참고

t1 = torch.cat([tensor, tensor, tensor], dim=1) # dim=1은 가로로 붙이고, dim=0은 세로로 붙임
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
## 산술 연산

# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T          # tensor과 tensor.T(tensor 전치) 행렬 곱
y2 = tensor.matmul(tensor.T)    # 위와 동일

y3 = torch.rand_like(y1)        # y1과 동일한 크기의 tensor 랜덤 생성
torch.matmul(tensor, tensor.T, out=y3)  # 메모리 효율적인 방식으로 행렬곱 실행(out 사용). 결과를 y3에 저장
print(y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor        # 각 요소별 곱
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
z3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [27]:
## 단일 요소 tensor

# 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환 가능

print(tensor)
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor(12.)
12.0 <class 'float'>


In [ ]:
## 바꿔치기 연산 : 연산 결과를 피연산자(operand)에 저장하는 연산

# _ 접미사를 가짐.
# ex) x.copy_(y), x.t_() 는 x를 변경.
# call by reference와 비슷함

print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

# 참고: 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서, 사용을 권장하지 않습니다.

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [29]:
## Numpy 변환(Bridge)
# CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경된다.

# tensor를 numpy 배열로 변경하기

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")


t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [30]:
# tensor의 변경 사항이 numpy에 저장

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [33]:
# numpy 배열을 tensor로 변환하기

n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
